# Generated by Django 3.2.5 on 2021-10-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
